name: Add User to Organization

on:
  issues:
    types: [opened]

jobs:
  add-user:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Request Membership' # Ensure it matches the issue template title
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Invite User to Organization
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Extracting issue body..."
          ISSUE_BODY=$(jq -r '.issue.body' < $GITHUB_EVENT_PATH)
          echo "Issue body: $ISSUE_BODY"

          # echo "Extracting username from issue body using regex..."
          # USERNAME=$(echo "$ISSUE_BODY" | grep -oP '(?<=### GitHub Username\n<!-- Please provide your GitHub username -->\n@)\w+')
          # echo "Extracted username: $USERNAME"
          
          # if [ -z "$USERNAME" ]; then
            echo "Trying alternative pattern..."
            USERNAME=$(echo "$ISSUE_BODY" | grep -oP '(?<=<!-- Please provide your GitHub username -->\s*@)\w+')
            echo "Extracted username with alternative pattern: $USERNAME"
          fi

          if [ -n "$USERNAME" ]; then
            echo "Sending invitation to $USERNAME..."
            curl -v -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/orgs/GI-Low/memberships/$USERNAME
          else
            echo "No username found in the issue body."
            exit 1
